ifeq ($(USE_PREBUILD_GPS_BLOB), yes)

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := gps.$(TARGET_BOARD_PLATFORM)
LOCAL_SRC_FILES_64 := arm64-v8a/gps.mt6755.so
LOCAL_SRC_FILES_32 := armabei-v7a/gps.mt6755.so
LOCAL_MULTILIB := both
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_RELATIVE_PATH := hw
include $(BUILD_PREBUILT)

endif